UPDATE history_insentif set id_karyawan = '20140201' where period_name = 'Samaun';
UPDATE history_insentif set id_karyawan = '20140202' where period_name = 'Solihi';
UPDATE history_insentif set id_karyawan = '20140203' where period_name = 'Misran';
UPDATE history_insentif set id_karyawan = '20140204' where period_name = 'Sudin';
UPDATE history_insentif set id_karyawan = '20140205' where period_name = 'Kenedi';
UPDATE history_insentif set id_karyawan = '20140206' where period_name = 'Mailan';
UPDATE history_insentif set id_karyawan = '20140207' where period_name = 'A Gani';
UPDATE history_insentif set id_karyawan = '20140208' where period_name = 'Sarwani';
UPDATE history_insentif set id_karyawan = '20140209' where period_name = 'Boby Novianto';
UPDATE history_insentif set id_karyawan = '20140210' where period_name = 'Sandra Akbar';
UPDATE history_insentif set id_karyawan = '20140211' where period_name = 'Madam Saprianto';
UPDATE history_insentif set id_karyawan = '20140212' where period_name = 'Darsito';
UPDATE history_insentif set id_karyawan = '20140213' where period_name = 'Tri Noor';
UPDATE history_insentif set id_karyawan = '20140214' where period_name = 'Abdul Munad';
UPDATE history_insentif set id_karyawan = '20140215' where period_name = 'Supariman';
UPDATE history_insentif set id_karyawan = '20140216' where period_name = 'Darmawan';
UPDATE history_insentif set id_karyawan = '20140217' where period_name = 'A Fauzi';
UPDATE history_insentif set id_karyawan = '20140218' where period_name = 'Darwis Harun';
UPDATE history_insentif set id_karyawan = '20140219' where period_name = 'Ramdani';
UPDATE history_insentif set id_karyawan = '20140220' where period_name = 'Romli Nantjek';
UPDATE history_insentif set id_karyawan = '20140221' where period_name = 'Dwi Ansyah';
UPDATE history_insentif set id_karyawan = '20140222' where period_name = 'Afridol Primanto';
UPDATE history_insentif set id_karyawan = '20140223' where period_name = 'Cikyam';
UPDATE history_insentif set id_karyawan = '20140224' where period_name = 'Aprilah';
UPDATE history_insentif set id_karyawan = '20140225' where period_name = 'Faisal Suleh';
UPDATE history_insentif set id_karyawan = '20140226' where period_name = 'Yuli Wahyono';
UPDATE history_insentif set id_karyawan = '20140227' where period_name = 'Herawaty';
UPDATE history_insentif set id_karyawan = '20140228' where period_name = 'Arie Firnandy';
UPDATE history_insentif set id_karyawan = '20140229' where period_name = 'Yuliono';
UPDATE history_insentif set id_karyawan = '20140230' where period_name = 'Andi';
UPDATE history_insentif set id_karyawan = '20140231' where period_name = 'Hamzah';
UPDATE history_insentif set id_karyawan = '20140232' where period_name = 'KGS Ahmad Firdaus';
UPDATE history_insentif set id_karyawan = '20140233' where period_name = 'Desna Alfrezy';
UPDATE history_insentif set id_karyawan = '20140234' where period_name = 'Indra Feri';
UPDATE history_insentif set id_karyawan = '20140235' where period_name = 'Suharyanto';
UPDATE history_insentif set id_karyawan = '20140236' where period_name = 'Subandi';
UPDATE history_insentif set id_karyawan = '20140237' where period_name = 'Nurzuwaidi';
UPDATE history_insentif set id_karyawan = '20140238' where period_name = 'Iskandar';
UPDATE history_insentif set id_karyawan = '20140239' where period_name = 'Didi Hardiansyah';
UPDATE history_insentif set id_karyawan = '20140240' where period_name = 'Nawi';
UPDATE history_insentif set id_karyawan = '20140241' where period_name = 'Tom Sien';
UPDATE history_insentif set id_karyawan = '20140242' where period_name = 'Doris Tupandi';
UPDATE history_insentif set id_karyawan = '20140243' where period_name = 'Riduan';
UPDATE history_insentif set id_karyawan = '20140244' where period_name = 'Sutarman Wijaya';
UPDATE history_insentif set id_karyawan = '20140245' where period_name = 'Sardy';
UPDATE history_insentif set id_karyawan = '20140246' where period_name = 'Tedy';
UPDATE history_insentif set id_karyawan = '20140247' where period_name = 'Darun';
UPDATE history_insentif set id_karyawan = '20140248' where period_name = 'Veri Heriyanto';
UPDATE history_insentif set id_karyawan = '20140249' where period_name = 'Aprianto';
UPDATE history_insentif set id_karyawan = '20140250' where period_name = 'Ken Arok';
UPDATE history_insentif set id_karyawan = '20140251' where period_name = 'Darsono';
UPDATE history_insentif set id_karyawan = '20140252' where period_name = 'Sutarman';
UPDATE history_insentif set id_karyawan = '20140253' where period_name = 'Erlansyah';
UPDATE history_insentif set id_karyawan = '20140254' where period_name = 'Norvid';
UPDATE history_insentif set id_karyawan = '20140255' where period_name = 'Hendra';
UPDATE history_insentif set id_karyawan = '20140256' where period_name = 'Fernando';
UPDATE history_insentif set id_karyawan = '20140257' where period_name = 'Kadavi';
UPDATE history_insentif set id_karyawan = '20140258' where period_name = 'Hartono';
UPDATE history_insentif set id_karyawan = '20140259' where period_name = 'Selamet';
UPDATE history_insentif set id_karyawan = '20140260' where period_name = 'Rudi Iskandar';
UPDATE history_insentif set id_karyawan = '20140261' where period_name = 'Maulana Eko';
UPDATE history_insentif set id_karyawan = '20140262' where period_name = 'Asnawi';
UPDATE history_insentif set id_karyawan = '20140263' where period_name = 'Surpin';
UPDATE history_insentif set id_karyawan = '20140264' where period_name = 'Madamin';
UPDATE history_insentif set id_karyawan = '20140265' where period_name = 'Suryadi';
UPDATE history_insentif set id_karyawan = '20140266' where period_name = 'Amir Hamzah';
UPDATE history_insentif set id_karyawan = '20140267' where period_name = 'Ishak';
UPDATE history_insentif set id_karyawan = '20140268' where period_name = 'Neta';
UPDATE history_insentif set id_karyawan = '20140269' where period_name = 'Wani';
UPDATE history_insentif set id_karyawan = '20140270' where period_name = 'Adi Chandra';
UPDATE history_insentif set id_karyawan = '20140271' where period_name = 'K. Solihin';
UPDATE history_insentif set id_karyawan = '20140272' where period_name = 'Marnoto';
UPDATE history_insentif set id_karyawan = '20140273' where period_name = 'Irwan';
UPDATE history_insentif set id_karyawan = '20140274' where period_name = 'Sarti';
UPDATE history_insentif set id_karyawan = '20140275' where period_name = 'Supardi';
UPDATE history_insentif set id_karyawan = '20140276' where period_name = 'Malan';
UPDATE history_insentif set id_karyawan = '20140277' where period_name = 'Sumiati';
UPDATE history_insentif set id_karyawan = '20140278' where period_name = 'Ansori';
UPDATE history_insentif set id_karyawan = '20140279' where period_name = 'M. Adriansyah';
UPDATE history_insentif set id_karyawan = '20140280' where period_name = 'Daud';
UPDATE history_insentif set id_karyawan = '20140281' where period_name = 'Rahmat Hidayat';
UPDATE history_insentif set id_karyawan = '20140282' where period_name = 'Akun';
UPDATE history_insentif set id_karyawan = '20140283' where period_name = 'Aan';
UPDATE history_insentif set id_karyawan = '20140284' where period_name = 'Fery';
UPDATE history_insentif set id_karyawan = '20140285' where period_name = 'Ahan';
UPDATE history_insentif set id_karyawan = '20140286' where period_name = 'Leman';
UPDATE history_insentif set id_karyawan = '20140287' where period_name = 'Alung';
UPDATE history_insentif set id_karyawan = '20140288' where period_name = 'Johan';
UPDATE history_insentif set id_karyawan = '20140289' where period_name = 'Sugianto';
UPDATE history_insentif set id_karyawan = '20140290' where period_name = 'Bambang';
UPDATE history_insentif set id_karyawan = '20140291' where period_name = 'Pekyang';
UPDATE history_insentif set id_karyawan = '20140292' where period_name = 'Asui';
UPDATE history_insentif set id_karyawan = '20140293' where period_name = 'Dencik';
UPDATE history_insentif set id_karyawan = '20140294' where period_name = 'Dedi Wahyudi';
UPDATE history_insentif set id_karyawan = '20140295' where period_name = 'Mad Supi';
UPDATE history_insentif set id_karyawan = '20140296' where period_name = 'Suwarsono';
UPDATE history_insentif set id_karyawan = '20140297' where period_name = 'Hasan';
UPDATE history_insentif set id_karyawan = '20140298' where period_name = 'Rozali';
UPDATE history_insentif set id_karyawan = '20140299' where period_name = 'Rozak';
UPDATE history_insentif set id_karyawan = '20140300' where period_name = 'Maya';
UPDATE history_insentif set id_karyawan = '20140301' where period_name = 'Abak';
